"use strict";

// Common English words grouped by length.
// Source: OpenSubtitles-2018 English frequency list (hermitdave/FrequencyWords)
// intersected with SOWPODS (international Scrabble word list). Contraction
// stems and explicitly rejected entries are excluded. Ordered by frequency.
const WORDS_BY_LEN = {
  2: [
    "TO", "IT", "OF", "IS", "IN", "WE", "ME", "HE",
    "MY", "ON", "DO", "NO", "BE", "SO", "GO", "IF",
    "UP", "AT", "OH", "AS", "AN", "US", "OR", "BY",
    "AM", "UH", "HI", "AH", "UM", "HA", "EH", "YO",
    "OW",
  ],
  3: [
    "YOU", "THE", "AND", "FOR", "WAS", "NOT", "ARE", "CAN",
    "BUT", "ALL", "GET", "SHE", "OUT", "HIM", "NOW", "ONE",
    "HER", "HOW", "GOT", "SEE", "DID", "WHO", "WHY", "LET",
    "HIS", "YES", "HAD", "OUR", "MAN", "SAY", "HEY", "HAS",
    "TOO", "WAY", "OFF", "ANY", "TWO", "SIR", "DAY", "GOD",
    "WON", "PUT", "NEW", "GUY", "OLD", "BIG", "LOT", "DAD",
    "MAY", "BAD", "ASK", "OWN", "CAR", "SON", "TRY", "MOM",
    "BOY", "JOB", "SAW", "HUH", "BIT", "YET", "MEN", "USE",
    "RUN", "END", "FEW", "AGO", "DIE", "SIT", "EAT", "PAY",
    "KID", "FAR", "ITS", "HIT", "FUN", "SET", "CUT", "WAR",
    "MET", "WOW", "BYE", "BUY", "GUN", "BED", "DOG", "SIX",
    "HOT", "RED", "TOP", "ASS", "WIN", "HMM", "AIR", "TEN",
    "SEX", "LIE", "BET", "OOH", "MAD", "EYE", "ACT", "LAW",
    "AGE", "BAG", "JOE", "RAN", "SUN", "BOX", "KEY", "BAR",
    "TOM", "SEA", "FIX", "TEA", "ICE", "SAD", "FLY", "BEN",
    "MUM", "ART", "CRY", "COP", "CAT", "MAX", "BUS", "RID",
    "OWE", "AAH", "FAT", "BOB", "YEP", "SHH", "FIT", "GAY",
    "LOW", "ARM", "GAS", "LEG", "SKY", "RAY", "POP", "VAN",
    "LEE", "LAY", "BEG", "HAT", "DUE", "CUP", "NOR", "DOC",
    "BRO", "OIL", "UGH", "DRY", "AYE", "LAB", "TIE", "DAN",
    "JOY", "FAN", "ADD", "PIG", "PAL", "WET", "NAH", "DIG",
    "COS", "ILL", "ATE", "LED", "MAP", "PER", "ODD", "SAT",
    "RAT", "HEH", "ROB", "EAR", "TED", "SUE", "TIP", "EGG",
    "COW", "CAB", "EVE", "ROW", "THY", "PIE", "POT", "SIN",
    "SPY", "HUG", "PEN", "FED", "BAY", "GEE", "BOW", "MAC",
  ],
  4: [
    "THAT", "WHAT", "THIS", "HAVE", "YOUR", "KNOW", "WITH", "JUST",
    "HERE", "THEY", "LIKE", "COME", "WELL", "YEAH", "WILL", "WANT",
    "GOOD", "FROM", "WHEN", "TIME", "OKAY", "BACK", "LOOK", "THEM",
    "WERE", "TAKE", "THEN", "BEEN", "TELL", "SOME", "NEED", "MORE",
    "DOWN", "MAKE", "VERY", "ONLY", "OVER", "LOVE", "MEAN", "SAID",
    "GIVE", "EVEN", "MUCH", "SURE", "HELP", "INTO", "FIND", "LIFE",
    "WORK", "MUST", "WAIT", "STOP", "CALL", "TALK", "AWAY", "THAN",
    "HOME", "LAST", "TOLD", "KEEP", "LONG", "DOES", "NAME", "EVER",
    "FEEL", "GUYS", "MADE", "DONE", "NICE", "GIRL", "FINE", "KIND",
    "STAY", "LEFT", "CAME", "HEAR", "SAME", "SHOW", "ELSE", "KILL",
    "NEXT", "CARE", "WENT", "DEAD", "MANY", "MIND", "BEST", "HELL",
    "REAL", "BABY", "ROOM", "MOVE", "MOST", "SEEN", "LIVE", "MISS",
    "SHIT", "BOTH", "ONCE", "HEAD", "USED", "IDEA", "KNEW", "HOLD",
    "DOOR", "SUCH", "FUCK", "ALSO", "TOOK", "WIFE", "DAYS", "MEET",
    "HARD", "GONE", "PLAY", "OPEN", "HOPE", "FACE", "LOST", "TURN",
    "CASE", "SAYS", "TRUE", "SOON", "EACH", "YEAR", "HAND", "PART",
    "KIDS", "LATE", "GAVE", "DAMN", "FIVE", "EYES", "SHUT", "EASY",
    "DEAL", "MINE", "BODY", "DEAR", "FOUR", "WORD", "HURT", "WISH",
    "WEEK", "REST", "FIRE", "GAME", "SIDE", "READ", "GOES", "ABLE",
    "LADY", "GETS", "SHOT", "CITY", "WALK", "TOWN", "HIGH", "HALF",
    "DIED", "COOL", "FREE", "WHOA", "TEAM", "BOYS", "LINE", "SEND",
    "NEWS", "FULL", "SAVE", "HATE", "FOOD", "FACT", "LORD", "PICK",
    "LOSE", "KING", "PLAN", "SORT", "BOSS", "SAFE", "BOOK", "SENT",
    "HOUR", "JOHN", "SICK", "POOR", "PAST", "GLAD", "HAIR", "JACK",
    "LUCK", "FAST", "COLD", "SEEM", "HANG", "TILL", "FELT", "SIGN",
    "LESS", "PULL", "BEAT", "DATE", "FALL", "SONG", "ROAD", "CALM",
    "DROP", "STEP", "LAND", "FEET", "DUDE", "NONE", "ONES", "PAIN",
    "PASS", "KEPT", "WAKE", "BUSY", "KISS", "SHIP", "SELL", "DARK",
    "RIDE", "BORN", "FILM", "WEAR", "SING", "BLUE", "NEAR", "ROCK",
    "PAID", "RING", "BILL", "ARMY", "LEAD", "FAIR", "FOOL", "CLUB",
    "TEST", "JOIN", "FEAR", "MIKE", "AREA", "BALL", "BOAT", "GOLD",
    "FISH", "MARK", "FELL", "DEEP", "STAR", "HIDE", "BANK", "TRIP",
    "LIST", "PARK", "SOUL", "RICH", "BLOW", "MESS", "CELL", "CARD",
    "MAMA", "DARE", "WALL", "SEAT", "COPS", "SAKE", "CUTE", "EVIL",
    "JOKE", "HUGE", "HOLY", "JAIL", "SHOP", "QUIT", "WINE", "SLOW",
    "CASH", "PUSH", "TREE", "GIFT", "BEAR", "GRAB", "BEER", "WIND",
    "UPON", "LOTS", "JUMP", "GROW", "AUNT", "MOON", "ARMS", "MATE",
    "FOOT", "CRAP", "TYPE", "RACE", "RISK", "NICK", "SPOT", "NINE",
    "DUTY", "SUIT", "BELL", "WEST", "LEGS", "HERO", "KICK", "WAYS",
    "TONY", "FORM", "SOLD", "HOLE", "LOCK", "BURN", "ROLL", "COST",
    "NOSE", "BAND", "BOMB", "NECK", "WARM", "DOGS", "WILD", "CAMP",
    "GUNS", "WHOM", "BIRD", "KEYS", "RAIN", "JANE", "SKIN", "COOK",
    "HALL", "DRUG", "MAIN", "DICK", "ROSE", "CODE", "NOTE", "CARS",
    "EAST", "LIES", "HELD", "RULE", "FILE", "TAPE", "MILK", "VOTE",
    "JAKE", "COPY", "PLUS", "CAKE", "CREW", "MEAT", "LIED", "SIZE",
    "LOUD", "PACK", "FEED", "FAKE", "PAPA", "ONTO", "VIEW", "FILL",
    "PRAY", "WASH", "HEAT", "MALE", "BASE", "LIFT", "DUMB", "NUTS",
    "OURS", "UGLY", "DRAW", "ANNA", "ENDS", "WEAK", "TINY", "DESK",
    "POOL", "GANG", "BITE", "BABE", "UNIT", "FATE", "FLAT", "PATH",
    "SOFT", "HARM", "SEES", "NOPE", "SNOW", "LAKE", "ROOF", "POST",
  ],
  5: [
    "THERE", "RIGHT", "ABOUT", "THINK", "GOING", "WOULD", "WHERE", "COULD",
    "NEVER", "SORRY", "THANK", "DOING", "THING", "THESE", "FIRST", "STILL",
    "THEIR", "AGAIN", "MAYBE", "OTHER", "AFTER", "NIGHT", "GREAT", "THOSE",
    "YEARS", "LEAVE", "MONEY", "PLACE", "WHICH", "HELLO", "HOUSE", "EVERY",
    "BEING", "WRONG", "WORLD", "MIGHT", "THREE", "TODAY", "FOUND", "WOMAN",
    "HEARD", "READY", "HAPPY", "WHOLE", "START", "WHILE", "SINCE", "GUESS",
    "BRING", "ALONE", "PHONE", "LOOKS", "UNTIL", "WANTS", "HEART", "WORRY",
    "LATER", "WATCH", "MUSIC", "YOUNG", "WATER", "STUFF", "UNDER", "DEATH",
    "CRAZY", "DRINK", "KNOWS", "TIMES", "CHECK", "HANDS", "MEANS", "POINT",
    "MAKES", "ASKED", "SLEEP", "QUITE", "CLOSE", "PARTY", "COMES", "SHALL",
    "STORY", "LEAST", "FIGHT", "GIRLS", "STAND", "CHILD", "HOURS", "SPEAK",
    "WOMEN", "TRUTH", "BLOOD", "BREAK", "TRUST", "YOURS", "SEEMS", "POWER",
    "HONEY", "TRIED", "FRONT", "HURRY", "ALONG", "LIGHT", "NEEDS", "CLEAR",
    "ORDER", "FUNNY", "BLACK", "ALIVE", "CAUSE", "AHEAD", "SIGHS", "TAKEN",
    "WHITE", "SMALL", "LIVES", "UNCLE", "EARTH", "SHOOT", "TOUCH", "SOUND",
    "HUMAN", "DRIVE", "BITCH", "DADDY", "WORDS", "DANCE", "CATCH", "SENSE",
    "KNOWN", "DREAM", "WRITE", "VOICE", "SWEET", "LUCKY", "QUIET", "WEEKS",
    "GIVEN", "FAULT", "TAKES", "LOVED", "LEARN", "EARLY", "CLEAN", "PIECE",
    "THROW", "WORTH", "QUICK", "STATE", "WORKS", "WEIRD", "CHIEF", "TIRED",
    "CLASS", "WORSE", "COURT", "MARRY", "MEANT", "MOVIE", "MOUTH", "MONTH",
    "LYING", "TRAIN", "SEVEN", "HOTEL", "ROUND", "BROKE", "FRANK", "TABLE",
    "BUDDY", "USING", "FLOOR", "SWEAR", "SPEND", "SPACE", "GROUP", "PEACE",
    "FORCE", "SHORT", "ENJOY", "CRIME", "HORSE", "COUNT", "HONOR", "LUNCH",
    "MILES", "RADIO", "IDIOT", "PAPER", "EIGHT", "COVER", "AGREE", "MAJOR",
    "STICK", "OFFER", "SMART", "RELAX", "BRAIN", "PROUD", "ANGRY", "PETER",
    "AGENT", "DRESS", "SCENE", "SAVED", "TOUGH", "FEELS", "DRUNK", "SHARE",
    "LAUGH", "SMELL", "OFTEN", "CALLS", "SPENT", "THIRD", "VISIT", "JUDGE",
    "MOVED", "PROVE", "LIVED", "QUEEN", "LOVES", "CARRY", "TEACH", "UPSET",
    "GREEN", "LIKED", "STORE", "LIKES", "DOUBT", "WROTE", "FIELD", "SOUTH",
    "GLASS", "DYING", "WHOSE", "PLANE", "NORTH", "MADAM", "TRUCK", "BOARD",
    "STUCK", "MAGIC", "RULES", "REACH", "GIVES", "HENRY", "DIRTY", "SHOES",
    "KNOCK", "HARRY", "WORST", "RIVER", "FINAL", "TURNS", "MATCH", "GASPS",
    "GRAND", "PRESS", "BLAME", "DRUGS", "RINGS", "NAMED", "PARIS", "BOOKS",
    "PRICE", "SMOKE", "FAVOR", "SMILE", "GUARD", "BEGIN", "ENEMY", "ALLOW",
    "APART", "STAGE", "BUNCH", "ADMIT", "NAMES", "STEAL", "JIMMY", "TWICE",
    "CROSS", "WASTE", "FIRED", "TASTE", "SILLY", "BUILD", "TRACK", "ABOVE",
    "VIDEO", "FRESH", "STOLE", "STUDY", "CROWD", "TREAT", "EMPTY", "LEVEL",
    "PLANS", "BUILT", "RAISE", "EXTRA", "HEAVY", "MOMMY", "BILLY", "KEEPS",
    "SHAME", "AWFUL", "LARGE", "LOCAL", "STONE", "GRACE", "PANTS", "BEACH",
    "FAITH", "KNIFE", "DEVIL", "TOMMY", "STARS", "FOLKS", "SHOWS", "BLIND",
    "GHOST", "TIGHT", "TELLS", "SPEED", "TRIAL", "OUGHT", "SPOKE", "ANGEL",
    "SUPER", "PLAYS", "AMONG", "COLOR", "PHOTO", "SIGHT", "GAMES", "COACH",
    "SERVE", "IDEAS", "OLDER", "TRICK", "TEETH", "TRULY", "BOBBY", "NURSE",
    "CHAIR", "HURTS", "ROGER", "BROWN", "HEADS", "SHIRT", "GUEST", "BEGAN",
    "CARDS", "BALLS", "ENDED", "USUAL", "AWARE", "PROOF", "CREAM", "TOTAL",
    "THREW", "BIRTH", "NOISE", "BIRDS", "BUCKS", "FOCUS", "OPENS", "EXIST",
    "ISSUE", "SWORD", "MAYOR", "STAFF", "LINES", "SPLIT", "ALARM", "SLEPT",
    "ENTER", "BRAVE", "MODEL", "BASED", "SCREW", "CARES", "STYLE", "SPARE",
    "SHAKE", "LOOSE", "PAINT", "NAKED", "SUGAR", "DOORS", "BLOCK", "FANCY",
    "CHEST", "TRADE", "MARIA", "STORM", "JERRY", "LOVER", "BREAD", "LEGAL",
  ],
  6: [
    "REALLY", "PEOPLE", "LITTLE", "PLEASE", "SHOULD", "BEFORE", "BETTER", "THINGS",
    "ALWAYS", "AROUND", "FATHER", "THANKS", "WANTED", "COMING", "COURSE", "ENOUGH",
    "MOTHER", "LISTEN", "FRIEND", "TRYING", "FAMILY", "CALLED", "PRETTY", "MATTER",
    "MYSELF", "SCHOOL", "SAYING", "ANYONE", "KILLED", "POLICE", "EXCUSE", "HAVING",
    "DOCTOR", "SECOND", "PERSON", "MINUTE", "FORGET", "CHANGE", "HAPPEN", "TAKING",
    "INSIDE", "MAKING", "AFRAID", "CHANCE", "ANYWAY", "NUMBER", "MOMENT", "NOBODY",
    "THOUGH", "SISTER", "BEHIND", "ALMOST", "REASON", "OFFICE", "COUPLE", "EITHER",
    "ANSWER", "STUPID", "MONTHS", "BECOME", "LIVING", "DINNER", "SOUNDS", "SCARED",
    "LAUGHS", "CANNOT", "ASKING", "MURDER", "STREET", "OTHERS", "FOLLOW", "MASTER",
    "RATHER", "LONGER", "WORKED", "LOOKED", "COFFEE", "RETURN", "SECRET", "SEEING",
    "FUTURE", "TURNED", "LADIES", "WONDER", "GIVING", "MOVING", "FIGURE", "STRONG",
    "NEEDED", "REPORT", "CHOICE", "FINISH", "DURING", "CAUGHT", "SYSTEM", "UNLESS",
    "ATTACK", "EXPECT", "EXCEPT", "THINKS", "ENTIRE", "TALKED", "ACROSS", "LOVELY",
    "HANDLE", "MIDDLE", "BOUGHT", "LETTER", "SIMPLE", "SINGLE", "FORGOT", "NORMAL",
    "GROUND", "CHARGE", "CRYING", "PRISON", "RECORD", "PUBLIC", "MISSED", "KILLER",
    "CHURCH", "CAMERA", "WITHIN", "BROKEN", "HONEST", "WINDOW", "HUNGRY", "BLOODY",
    "FRENCH", "BECAME", "ACCEPT", "LAWYER", "ISLAND", "EATING", "GRUNTS", "CHEERS",
    "VICTIM", "PLANET", "SEARCH", "DREAMS", "ARREST", "PASSED", "SUMMER", "ESCAPE",
    "CHOOSE", "DECIDE", "BOTHER", "HEAVEN", "PICKED", "ACTION", "ORDERS", "PLAYED",
    "NOTICE", "BATTLE", "GUILTY", "BIGGER", "CLOSED", "INDEED", "ENERGY", "HELPED",
    "LOCKED", "PLACES", "STARTS", "PRINCE", "THROAT", "HIDING", "SEEMED", "ENGINE",
    "WEAPON", "DOUBLE", "SPIRIT", "DANGER", "MEMORY", "ITSELF", "ACTING", "CLOSER",
    "GROANS", "LOSING", "FLIGHT", "NATURE", "CLIENT", "BOTTLE", "SIMPLY", "ANIMAL",
    "SHOWED", "HOPING", "FAMOUS", "ASLEEP", "BEAUTY", "DRIVER", "PLENTY", "COMMON",
    "BOTTOM", "GERMAN", "WALKED", "PAPERS", "LIGHTS", "FLYING", "AGREED", "JOHNNY",
    "CORNER", "FASTER", "FELLOW", "LEADER", "LEAVES", "GOTTEN", "PULLED", "HEALTH",
    "ADVICE", "BEYOND", "HARDLY", "COUSIN", "STATES", "PARDON", "CAREER", "TAUGHT",
    "MARTIN", "BREATH", "MARKET", "NEARLY", "BRIDGE", "CENTER", "UNITED", "TRAVEL",
    "PAYING", "TARGET", "BELONG", "REMAIN", "CREDIT", "EASIER", "STRIKE", "PIECES",
    "FEMALE", "MOVIES", "TICKET", "STOLEN", "PREFER", "SURELY", "CREATE", "AFFORD",
    "SOCIAL", "BODIES", "OPENED", "MISTER", "BULLET", "LATELY", "STAYED", "SEASON",
    "SHOWER", "FUCKED", "LONELY", "FORCED", "SETTLE", "WEIGHT", "HORSES", "SLOWLY",
    "MEMBER", "SIGNED", "GARDEN", "BRINGS", "FINGER", "ACCESS", "FAILED", "EASILY",
    "INSANE", "SIGNAL", "SPEECH", "BRIGHT", "REMIND", "DAMAGE", "AMOUNT", "MANAGE",
    "SAFETY", "HARDER", "DRINKS", "BURIED", "THEORY", "RUINED", "SPREAD", "SUDDEN",
    "SOONER", "CHEESE", "SPRING", "CASTLE", "HIDDEN", "ARTIST", "FOREST", "BARELY",
    "REGRET", "LESSON", "CAUSED", "POINTS", "DATING", "LIKELY", "NIGHTS", "POCKET",
    "SQUARE", "GENIUS", "WINTER", "TONGUE",
  ],
};

// Themed words.
const WORDS_THEMED = {
  2: [
    "OW", "AH", "GO", "NO",
  ],
  3: [
    "HIT", "RUN", "DIE", "CRY", "BAD", "ROT", "UGH",
    "AIM", "FOG", "WAR", "NIX", "SIN", "DIM", "BOO",
    "EEK", "CUT", "FOE", "ZAP", "DOT",
  ],
  4: [
    "KILL", "SHOT", "DEAD", "RAWR", "OUCH", "SLAY",
    "MAIM", "DARK", "LAMP", "FIRE", "BURN", "ARGH",
    "DOOM", "HUNT", "FEAR", "BOOM", "BANG", "JOLT",
    "BEEP", "BOOP", "DASH", "EVIL", "VOID"
  ],
  5: [
    "FIEND", "BRUTE", "HORDE", "BLOOD", "DECAY",
    "SHOOT", "BLAST", "TORCH", "FLARE", "FIGHT",
    "NIGHT", "LIGHT", "SKULL", "CURSE", "DEATH",
    "SWARM", "ALARM", "BLEED", "PANIC", "SLAIN",
    "QUAKE", "QUELL", "QUICK", "EXILE"
  ],
  6: [
    "SIGNAL", "STRIKE", "ATTACK", "ESCAPE", "BATTLE",
    "DAMAGE", "DANGER", "TARGET", "ASSAIL", "BEHEAD",
    "MENACE", "AVENGE",
  ],
};

function wordsOfLengths(lengths, dict) {
  const source = dict || WORDS_THEMED;
  const out = [];
  for (const L of lengths) if (source[L]) out.push(...source[L]);
  return out;
}

const WORDS_2    = wordsOfLengths([2]);
const WORDS_3_4  = wordsOfLengths([3, 4]);
const WORDS_5_6  = wordsOfLengths([5, 6]);
const WORDS_FAST = wordsOfLengths([2]);
