name = "aldis"
main = "worker.js"
compatibility_date = "2026-04-18"

[assets]
directory = "./"
binding = "ASSETS"

[[routes]]
pattern = "aldis.gelatolabs.xyz"
custom_domain = true

[[kv_namespaces]]
binding = "SCORES"
id = "e170efe8f6ea42c2a48bf306881e97e7"
preview_id = "2dff39920b004b06a28302f18cccb253"
